set(BLA_VENDOR OpenBLAS)
# set(BLA_VENDOR Intel10_64lp)
find_package(BLAS REQUIRED)
if(BLAS_FOUND)
  message("-- BLAS libs @ ${BLAS_LIBRARIES}")
endif(BLAS_FOUND)

if( ${BLA_VENDOR} STREQUAL "Intel10_64lp" )
  add_compile_definitions(BLAS_USE_INTEL_MKL)
endif()

find_package(LAPACK REQUIRED)

if(LAPACK_FOUND)
  message(STATUS "LAPACK found.")
  message(STATUS "LAPACK include directories: ${LAPACK_INCLUDE_DIRS}")
  message(STATUS "LAPACK libraries: ${LAPACK_LIBRARIES}")
else()
  message(FATAL_ERROR "LAPACKE not found.")
endif()
